// Словари интерфейса. ⚠️ Грузинские строки желательно вычитать носителю языка.
export const LANGS = ["ru", "en", "ka"];

export const DICT = {
  ru: {
    nav_sale: "Продажа", nav_rent: "Аренда", nav_new: "Новостройки", nav_daily: "Посуточно", nav_services: "Услуги",
    search: "Поиск", login: "Войти", cabinet: "Кабинет", sell: "Сдать / продать", favorites: "Избранное", allGeorgia: "Вся Грузия",
    hero_pre: "Недвижимость в", hero_post: "— купить, продать, снять или сдать",
    hero_sub: "Проверенные квартиры, дома и апартаменты по всей Грузии — без дублей и фейков. Прозрачные цены, честные условия и помощь местной команды на каждом шаге сделки.",
    georgia: "Грузии",
    tab_sale: "Продажа", tab_rent: "Аренда", tab_new: "Новостройки", tab_daily: "Посуточно",
    f_city: "Город", f_anyCity: "Любой город", f_type: "Тип", f_anyType: "Любой тип", f_priceTo: "Цена до, $", f_show: "Показать объекты", f_map: "На карте",
    st_verified: "проверенные объекты", st_commission: "скрытых комиссий", st_support: "поддержка", st_langs: "языка: RU · EN · GE",
    // каталог
    cat_found: "Найдено", cat_objects: "объект(ов)", chip_all: "Все", f_rooms: "Комнат", f_anyRooms: "Любая", f_studio: "Студия",
    f_yearFrom: "Год от", f_priceFrom: "Цена от, $", f_areaFrom: "Площадь от, м²", f_areaTo: "Площадь до, м²", f_reset: "Сбросить", f_noCommission: "Без комиссии", cat_empty: "По этому фильтру пока нет объектов.",
    // футер
    foot_about: "Управление, аренда и продажа недвижимости в Грузии. Скоро — новые города и мобильное приложение.",
    foot_realty: "Недвижимость", foot_company: "Компания", foot_mgmt: "Управление недвижимостью", foot_cleaning: "Клининг", foot_realtors: "Риелторы",
    foot_about_l: "О компании", foot_contacts: "Контакты", foot_terms: "Условия", foot_privacy: "Конфиденциальность",
    // карточки
    rooms_short: "комн.", per_m2: "за м²", deal_sale: "Продажа", deal_rent: "Аренда", deal_daily: "Посуточно",
    badge_jk: "ЖК", badge_house: "Дом", w_from: "от", w_objects: "объект(ов)",
    // страница объекта/дома
    crumb_home: "Главная", crumb_catalog: "Каталог",
    cta_daily: "Забронировать даты", cta_rent: "Снять — оставить заявку", cta_view: "Забронировать просмотр",
    sp_type: "Тип", sp_area: "Площадь", sp_rooms: "Комнат", sp_bath: "Санузлов", sp_floor: "Этаж", sp_year: "Год постройки", sp_district: "Район", sp_deal: "Сделка", sp_complex: "ЖК / дом",
    boost_badge: "⭐ Продвигается",
    about_h: "Об объекте", about_p: "Готов к заселению, актуальные документы. Подходит как для проживания, так и под сдачу гостям.",
    near_h: "Что рядом", near_p: "Море и набережная в пешей доступности, рядом кафе, магазины и транспорт. Развитая инфраструктура района.",
    why_h: "Почему через Baylux", why_p: "Объект проверен нашей командой: документы, реальные фото, честная цена. Поможем с просмотром и сделкой, при желании возьмём в управление.",
    mgmt_btn: "Отдать похожую в управление", all_in: "Все объекты в", team: "Команда Baylux", team_sub: "Ответим за 5 минут · RU / EN / GE",
    bld_objects_here: "объект(ов) в продаже и аренде", bld_about_complex: "О комплексе", bld_about_house: "О доме", bld_units_here: "Объекты в этом доме",
    th_object: "Объект", th_area: "Площадь", th_floor: "Этаж", th_deal: "Сделка", th_price: "Цена",
    bld_cta_title: "Интересует объект в", bld_cta_sub: "Подберём под бюджет и задачу, организуем просмотр.", bld_lead: "Оставить заявку", bld_mgmt: "Сдать квартиру здесь в управление",
    // категории и подменю
    cat_apartment: "Квартиры", cat_house: "Дома", cat_commercial: "Коммерция", cat_office: "Офисы", cat_warehouse: "Склады", cat_land: "Участки", cat_garage: "Гаражи и паркинги", cat_jk: "Жилые комплексы", cat_cottage: "Коттеджи",
    cat_title: "Категории недвижимости", cat_subtitle: "Быстрый переход к нужному разделу — продажа, аренда, посуточно и услуги.", show_all: "Показать все", collapse: "Свернуть",
    t_apartment: "Квартира", t_studio: "Студия", t_house: "Дом", t_commercial: "Коммерция", t_office: "Офис", t_land: "Участок", t_garage: "Гараж", t_newbuild: "Новостройка",
    // форма добавления/редактирования
    af_country: "Страна", af_city: "Город", af_deal: "Тип сделки", af_type: "Тип объекта",
    af_complex: "Название ЖК / дома — по желанию", af_complex_ph: "напр. ЖК Orbi City (необязательно)",
    af_address: "Адрес (улица, дом)", af_address_ph: "ул. Шерифа Химшиашвили, 1",
    af_mapnote: "Точка на карте — ставится по адресу автоматически. Можно поправить кликом (включите спутник):",
    af_geo_auto: "📍 Точка поставлена по адресу — проверьте и при необходимости передвиньте кликом по карте.",
    af_geo_manual: "✓ Точка выбрана вручную.", af_geo_set: "✓ Точка выбрана", af_geo_hint: "Введите адрес — точка встанет сама, либо кликните по карте",
    af_price: "Цена", af_currency: "Валюта", af_area: "Площадь, м²", af_rooms: "Комнат", af_bath: "Санузлов", af_floor: "Этаж", af_year: "Год постройки",
    af_about: "Описание", af_about_ph: "Кратко об объекте", af_amen: "Удобства (по желанию)", af_nc: "Без комиссии с покупателя",
    af_phone: "Телефон для связи — Грузия, +995 (обязательно)", af_tg: "Telegram для связи (@username) — по желанию", af_tg_ph: "@username (необязательно)",
    af_cur_photos: "Текущие фото (нажмите ✕, чтобы убрать)", af_add_photos: "Добавить ещё фото", af_photos: "Фото (до 10, сжимаются автоматически)", af_newphotos: "новых фото",
    af_saving: "Сохраняю…", af_submit: "Отправить на модерацию", af_submit_edit: "Сохранить и отправить на модерацию", af_err: "Ошибка отправки. Проверьте поля и попробуйте снова.",
    af_alert_addr: "Укажите адрес объекта.", af_alert_phone: "Укажите грузинский номер телефона (+995). Например: +995 555 12 34 56.",
    af_done_add_h: "✅ Объявление отправлено на модерацию", af_done_edit_h: "✅ Изменения отправлены на модерацию",
    af_done_add_p: "Мы проверим его и опубликуем.", af_done_edit_p: "Объявление снято с публикации и появится снова после повторной проверки.",
    af_done_tail: "Статус — в разделе «Мои объявления».", af_my: "Мои объявления",
    am_furniture: "Мебель", am_balcony: "Балкон", am_terrace: "Терраса", am_parking: "Парковка", am_euro: "Ремонт «евро»", am_norenov: "Без ремонта", am_ac: "Кондиционер", am_elevator: "Лифт",
    // личный кабинет
    cab_title: "Личный кабинет", cab_login_p: "Войдите через Telegram — увидите свои объявления, поданные через бота, и их статусы.", cab_or: "или войдите виджетом Telegram:",
    cab_bot_a: "Объявления добавляются в боте", cab_bot_b: "(команда /start или меню).",
    my_title: "Мои объявления", my_logout: "Выйти", cab_objs: "Ваши объекты", cab_addnew: "Добавить новый — в боте @baylux_leads_bot (/start).",
    my_pending: "На модерации", my_approved: "Опубликовано", my_rejected: "Снято / отклонено",
    my_view: "Посмотреть →", my_notvisible: "на сайте не виден", my_edit: "✏️ Редактировать", my_del: "🗑 Удалить", my_deleting: "Удаляю…",
    my_empty: "Пока нет объявлений. Откройте бота и отправьте /start.", my_del_confirm: "Удалить это объявление? Действие необратимо.", my_del_fail: "Не удалось удалить. Попробуйте позже.", my_neterr: "Ошибка сети.",
    // статические страницы
    ab_title: "О компании Baylux",
    ab_p1: "Baylux — компания по недвижимости в Батуми (Грузия). Мы помогаем купить, продать, снять и сдать жильё, а также берём объекты в управление под ключ. Работаем как местная команда — приезжаем, показываем и сопровождаем сделку на месте, а не из колл-центра.",
    ab_h_do: "Что мы делаем", ab_do1: "Продажа недвижимости — первичка (новостройки) и вторичка.", ab_do2: "Аренда — долгосрочная и посуточная.", ab_do3: "Управление недвижимостью — гости, уборка, ремонт, отчёты.", ab_do4: "Клининг и сопутствующие услуги.",
    ab_h_why: "Почему Baylux", ab_why1: "Проверенные объекты — без дублей и фейков.", ab_why2: "Прозрачные цены и условия, без скрытых комиссий.", ab_why3: "Поддержка на русском, английском и грузинском.",
    ab_h_plans: "Планы", ab_plans_p: "Сейчас мы работаем в Батуми. В планах — другие города Грузии и собственное мобильное приложение.", ab_btn_add: "Разместить объявление", ab_btn_contacts: "Контакты",
    co_title: "Контакты", co_p: "Ответим за 5 минут. Пишите удобным способом — на русском, английском или грузинском.",
    co_h_where: "Где мы", co_where: "📍 Батуми, Грузия. Работаем по всему городу и пригородам (Гонио, Махинджаури, Чакви).",
    co_h_post: "Разместить объект", co_post: "Сдать или продать недвижимость можно прямо на сайте — кнопка «Сдать / продать», или через нашего Telegram-бота @baylux_leads_bot.", co_foot: "Baylux · недвижимость в Батуми, Грузия.",
    tm_title: "Условия использования", tm_disclaimer: "Базовая редакция. Итоговый текст должен быть проверён юристом с учётом законодательства Грузии.",
    tm_h1: "1. Общие положения", tm_p1: "Сайт Baylux — площадка для размещения и поиска объявлений о недвижимости в Батуми. Пользуясь сайтом, вы соглашаетесь с настоящими условиями.",
    tm_h2: "2. Объявления и модерация", tm_p2: "Объявления размещаются пользователями и проходят проверку модератором перед публикацией. Baylux вправе отклонить или снять объявление, нарушающее правила, содержащее недостоверные данные или чужой контент.",
    tm_h3: "3. Ответственность", tm_p3: "За достоверность сведений и фотографий в объявлении отвечает разместивший его пользователь. Baylux не является стороной сделки между пользователями, если иное не оговорено отдельно.",
    tm_h4: "4. Контент", tm_p4: "Размещая объявление, пользователь подтверждает, что обладает правами на используемые фото и описания и даёт согласие на их публикацию на сайте.",
    tm_h5: "5. Контакты", tm_p5: "По вопросам — раздел «Контакты». Условия могут обновляться; актуальная редакция публикуется на этой странице.",
    pv_title: "Политика конфиденциальности", pv_h_what: "Какие данные мы обрабатываем",
    pv_what1: "Контакт для связи (телефон, @username), указанный при размещении объявления.", pv_what2: "Идентификатор Telegram при входе через Telegram.", pv_what3: "Данные объявления: тип, адрес, цена, описание, фотографии, точка на карте.",
    pv_h_why: "Зачем", pv_why: "Чтобы публиковать объявления, связывать их с вашим аккаунтом, проводить модерацию и связываться с вами по объекту.",
    pv_h_store: "Хранение", pv_store: "Данные хранятся у поставщика инфраструктуры (Supabase) и используются только для работы сервиса. Мы не продаём ваши данные третьим лицам.",
    pv_h_rights: "Ваши права", pv_rights: "Вы можете удалить свои объявления в разделе «Мои объявления» или запросить удаление аккаунта, написав в «Контакты».",
    add_title: "Разместить объявление", add_login_p: "Сначала войдите через Telegram — объявление привяжется к вашему аккаунту, и вы сможете им управлять.", add_intro: "Заполните данные, отметьте точку на карте и добавьте фото. После проверки модератором объявление появится на сайте. Статус — в разделе «Мои объявления».",
    fav_title: "Избранное", fav_empty: "Пока пусто. Нажимайте ♡ на карточках объектов — они появятся здесь.", fav_to_catalog: "Открыть каталог →", fav_open: "Открыть", fav_remove: "Убрать",
    // главная страница
    home_map_h: "Жилые комплексы и дома на карте", home_map_p: "Один пин — один дом. Откройте здание и посмотрите все квартиры, что в нём продаются и сдаются.", home_map_btn: "Открыть каталог с фильтрами →",
    home_fresh_h: "Свежие объекты", home_fresh_p: "Последние квартиры и апартаменты в базе Baylux.",
    svc_h: "Что мы делаем", svc_p: "Не просто витрина объявлений — полный цикл работы с недвижимостью в Грузии.",
    svc_mgmt_h: "Управление", svc_mgmt_p: "Доверьте нам квартиру — займёмся гостями, уборкой, ремонтом и отчётами. Вы получаете доход, мы берём рутину.", svc_mgmt_btn: "Отдать в управление →",
    svc_rent_h: "Аренда", svc_rent_p: "Посуточно для гостей города и долгосрочно для тех, кто переезжает. Честные цены, проверенные объекты, договор.", svc_rent_btn: "Снять или сдать →",
    svc_sale_h: "Продажа и инвестиции", svc_sale_p: "Поможем купить квартиру для жизни или вложиться в новостройку у моря. Сопровождаем сделку от показа до ключей.", svc_sale_btn: "Купить или продать →",
    why_local_h: "Местные", why_local_p: "Команда в Батуми — приедем, покажем, поможем на месте.",
    why_nodup_h: "Без дублей", why_nodup_p: "Чистая база: один объект — одно объявление, без мусора.",
    why_clear_h: "Прозрачно", why_clear_p: "Реальные цены и условия. Без скрытых комиссий.",
    why_fast_h: "Быстро", why_fast_p: "Заявка и бронь через сайт или WhatsApp — за минуту.",
  },
  en: {
    nav_sale: "Buy", nav_rent: "Rent", nav_new: "New buildings", nav_daily: "Daily", nav_services: "Services",
    search: "Search", login: "Sign in", cabinet: "Account", sell: "Sell / rent out", favorites: "Saved", allGeorgia: "All Georgia",
    hero_pre: "Real estate in", hero_post: "— buy, sell, rent or let",
    hero_sub: "Verified apartments, houses and aparthotels across Georgia — no duplicates or fakes. Transparent prices, fair terms and help from a local team at every step.",
    georgia: "Georgia",
    tab_sale: "Sale", tab_rent: "Rent", tab_new: "New builds", tab_daily: "Daily",
    f_city: "City", f_anyCity: "Any city", f_type: "Type", f_anyType: "Any type", f_priceTo: "Price up to, $", f_show: "Show objects", f_map: "On map",
    st_verified: "verified objects", st_commission: "hidden fees", st_support: "support", st_langs: "languages: RU · EN · GE",
    cat_found: "Found", cat_objects: "object(s)", chip_all: "All", f_rooms: "Rooms", f_anyRooms: "Any", f_studio: "Studio",
    f_yearFrom: "Year from", f_priceFrom: "Price from, $", f_areaFrom: "Area from, m²", f_areaTo: "Area to, m²", f_reset: "Reset", f_noCommission: "No commission", cat_empty: "No objects match this filter yet.",
    foot_about: "Property management, rent and sale in Georgia. New cities and a mobile app coming soon.",
    foot_realty: "Real estate", foot_company: "Company", foot_mgmt: "Property management", foot_cleaning: "Cleaning", foot_realtors: "Realtors",
    foot_about_l: "About", foot_contacts: "Contacts", foot_terms: "Terms", foot_privacy: "Privacy",
    rooms_short: "rooms", per_m2: "per m²", deal_sale: "Sale", deal_rent: "Rent", deal_daily: "Daily",
    badge_jk: "Complex", badge_house: "House", w_from: "from", w_objects: "object(s)",
    crumb_home: "Home", crumb_catalog: "Catalog",
    cta_daily: "Book dates", cta_rent: "Rent — send request", cta_view: "Book a viewing",
    sp_type: "Type", sp_area: "Area", sp_rooms: "Rooms", sp_bath: "Bathrooms", sp_floor: "Floor", sp_year: "Built", sp_district: "District", sp_deal: "Deal", sp_complex: "Complex / house",
    boost_badge: "⭐ Promoted",
    about_h: "About", about_p: "Ready to move in, valid documents. Suitable for living or short-term rental.",
    near_h: "Nearby", near_p: "Sea and promenade within walking distance, cafes, shops and transport nearby. Well-developed area.",
    why_h: "Why Baylux", why_p: "Verified by our team: documents, real photos, fair price. We help with viewing and the deal, and can take it under management.",
    mgmt_btn: "List a similar one for management", all_in: "All objects in", team: "Baylux team", team_sub: "We reply within 5 min · RU / EN / GE",
    bld_objects_here: "object(s) for sale and rent", bld_about_complex: "About the complex", bld_about_house: "About the house", bld_units_here: "Objects in this building",
    th_object: "Object", th_area: "Area", th_floor: "Floor", th_deal: "Deal", th_price: "Price",
    bld_cta_title: "Interested in an object in", bld_cta_sub: "We'll match your budget and arrange a viewing.", bld_lead: "Send request", bld_mgmt: "Put an apartment here under management",
    cat_apartment: "Apartments", cat_house: "Houses", cat_commercial: "Commercial", cat_office: "Offices", cat_warehouse: "Warehouses", cat_land: "Land plots", cat_garage: "Garages & parking", cat_jk: "Residential complexes", cat_cottage: "Cottages",
    cat_title: "Property categories", cat_subtitle: "Quick access — sale, rent, daily and services.", show_all: "Show all", collapse: "Collapse",
    t_apartment: "Apartment", t_studio: "Studio", t_house: "House", t_commercial: "Commercial", t_office: "Office", t_land: "Land plot", t_garage: "Garage", t_newbuild: "New building",
    af_country: "Country", af_city: "City", af_deal: "Deal type", af_type: "Property type",
    af_complex: "Complex / building name — optional", af_complex_ph: "e.g. Orbi City (optional)",
    af_address: "Address (street, building)", af_address_ph: "Sherif Khimshiashvili St, 1",
    af_mapnote: "Map point — set automatically from the address. You can adjust it by clicking (enable satellite):",
    af_geo_auto: "📍 Point set from the address — check it and move it by clicking the map if needed.",
    af_geo_manual: "✓ Point selected manually.", af_geo_set: "✓ Point selected", af_geo_hint: "Enter the address — the point will appear, or click on the map",
    af_price: "Price", af_currency: "Currency", af_area: "Area, m²", af_rooms: "Rooms", af_bath: "Bathrooms", af_floor: "Floor", af_year: "Year built",
    af_about: "Description", af_about_ph: "Briefly about the property", af_amen: "Amenities (optional)", af_nc: "No buyer commission",
    af_phone: "Contact phone — Georgia, +995 (required)", af_tg: "Telegram for contact (@username) — optional", af_tg_ph: "@username (optional)",
    af_cur_photos: "Current photos (click ✕ to remove)", af_add_photos: "Add more photos", af_photos: "Photos (up to 10, auto-compressed)", af_newphotos: "new photos",
    af_saving: "Saving…", af_submit: "Submit for moderation", af_submit_edit: "Save and submit for moderation", af_err: "Submit error. Check the fields and try again.",
    af_alert_addr: "Please enter the property address.", af_alert_phone: "Please enter a Georgian phone number (+995). For example: +995 555 12 34 56.",
    af_done_add_h: "✅ Listing submitted for moderation", af_done_edit_h: "✅ Changes submitted for moderation",
    af_done_add_p: "We'll review and publish it.", af_done_edit_p: "The listing was unpublished and will reappear after re-review.",
    af_done_tail: "Status is in the “My listings” section.", af_my: "My listings",
    am_furniture: "Furniture", am_balcony: "Balcony", am_terrace: "Terrace", am_parking: "Parking", am_euro: "Renovated (euro)", am_norenov: "No renovation", am_ac: "Air conditioning", am_elevator: "Elevator",
    cab_title: "Account", cab_login_p: "Log in with Telegram to see the listings you submitted via the bot and their status.", cab_or: "or log in with the Telegram widget:",
    cab_bot_a: "Listings are added in the bot", cab_bot_b: "(command /start or menu).",
    my_title: "My listings", my_logout: "Log out", cab_objs: "Your listings", cab_addnew: "Add a new one in the bot @baylux_leads_bot (/start).",
    my_pending: "Under review", my_approved: "Published", my_rejected: "Removed / rejected",
    my_view: "View →", my_notvisible: "not visible on the site", my_edit: "✏️ Edit", my_del: "🗑 Delete", my_deleting: "Deleting…",
    my_empty: "No listings yet. Open the bot and send /start.", my_del_confirm: "Delete this listing? This cannot be undone.", my_del_fail: "Couldn't delete. Try again later.", my_neterr: "Network error.",
    ab_title: "About Baylux",
    ab_p1: "Baylux is a real-estate company in Batumi, Georgia. We help you buy, sell, rent and let property, and we also take properties under full management. We work as a local team — we come, show the property and handle the deal on the spot, not from a call center.",
    ab_h_do: "What we do", ab_do1: "Property sales — new builds (primary) and resale (secondary).", ab_do2: "Rentals — long-term and daily.", ab_do3: "Property management — guests, cleaning, repairs, reports.", ab_do4: "Cleaning and related services.",
    ab_h_why: "Why Baylux", ab_why1: "Verified listings — no duplicates or fakes.", ab_why2: "Transparent prices and terms, no hidden fees.", ab_why3: "Support in Russian, English and Georgian.",
    ab_h_plans: "Plans", ab_plans_p: "Right now we operate in Batumi. Next: other cities in Georgia and our own mobile app.", ab_btn_add: "Post a listing", ab_btn_contacts: "Contacts",
    co_title: "Contacts", co_p: "We reply within 5 minutes. Write to us however is convenient — in Russian, English or Georgian.",
    co_h_where: "Where we are", co_where: "📍 Batumi, Georgia. We cover the whole city and suburbs (Gonio, Makhinjauri, Chakvi).",
    co_h_post: "Post a property", co_post: "You can let or sell property right on the site — the “Sell / rent out” button, or via our Telegram bot @baylux_leads_bot.", co_foot: "Baylux · real estate in Batumi, Georgia.",
    tm_title: "Terms of use", tm_disclaimer: "Draft version. The final text must be reviewed by a lawyer in line with Georgian law.",
    tm_h1: "1. General", tm_p1: "The Baylux site is a platform for posting and searching real-estate listings in Batumi. By using the site you agree to these terms.",
    tm_h2: "2. Listings and moderation", tm_p2: "Listings are posted by users and reviewed by a moderator before publication. Baylux may reject or remove a listing that breaks the rules, contains false data or someone else's content.",
    tm_h3: "3. Liability", tm_p3: "The user who posted a listing is responsible for the accuracy of its information and photos. Baylux is not a party to the deal between users unless agreed separately.",
    tm_h4: "4. Content", tm_p4: "By posting a listing, the user confirms they hold the rights to the photos and descriptions used and consents to their publication on the site.",
    tm_h5: "5. Contacts", tm_p5: "For questions, see the “Contacts” section. The terms may be updated; the current version is published on this page.",
    pv_title: "Privacy policy", pv_h_what: "What data we process",
    pv_what1: "Contact details (phone, @username) provided when posting a listing.", pv_what2: "Telegram ID when logging in via Telegram.", pv_what3: "Listing data: type, address, price, description, photos, map point.",
    pv_h_why: "Why", pv_why: "To publish listings, link them to your account, run moderation and contact you about the property.",
    pv_h_store: "Storage", pv_store: "Data is stored with our infrastructure provider (Supabase) and used only to run the service. We do not sell your data to third parties.",
    pv_h_rights: "Your rights", pv_rights: "You can delete your listings in the “My listings” section or request account deletion via “Contacts”.",
    add_title: "Post a listing", add_login_p: "First log in with Telegram — the listing will be linked to your account and you'll be able to manage it.", add_intro: "Fill in the details, mark the point on the map and add photos. After a moderator's review the listing will appear on the site. Status is in the “My listings” section.",
    fav_title: "Favorites", fav_empty: "Nothing here yet. Tap ♡ on listing cards — they'll show up here.", fav_to_catalog: "Open catalog →", fav_open: "Open", fav_remove: "Remove",
    home_map_h: "Residential complexes and houses on the map", home_map_p: "One pin — one building. Open a building to see all apartments for sale and rent in it.", home_map_btn: "Open catalog with filters →",
    home_fresh_h: "Fresh listings", home_fresh_p: "The latest apartments and units in the Baylux database.",
    svc_h: "What we do", svc_p: "Not just a listings board — a full cycle of real-estate services in Georgia.",
    svc_mgmt_h: "Management", svc_mgmt_p: "Hand us your apartment — we handle guests, cleaning, repairs and reports. You get the income, we take the routine.", svc_mgmt_btn: "Hand over to management →",
    svc_rent_h: "Rent", svc_rent_p: "Daily for city guests and long-term for those relocating. Fair prices, verified properties, a contract.", svc_rent_btn: "Rent or let out →",
    svc_sale_h: "Sales and investment", svc_sale_p: "We'll help you buy a home to live in or invest in a new build by the sea. We guide the deal from viewing to keys.", svc_sale_btn: "Buy or sell →",
    why_local_h: "Local", why_local_p: "A team in Batumi — we come, show and help on the spot.",
    why_nodup_h: "No duplicates", why_nodup_p: "A clean database: one property — one listing, no clutter.",
    why_clear_h: "Transparent", why_clear_p: "Real prices and terms. No hidden fees.",
    why_fast_h: "Fast", why_fast_p: "Request and booking via the site or WhatsApp — in a minute.",
  },
  ka: {
    nav_sale: "ყიდვა", nav_rent: "ქირა", nav_new: "ახალი კორპუსები", nav_daily: "დღიურად", nav_services: "სერვისები",
    search: "ძებნა", login: "შესვლა", cabinet: "კაბინეტი", sell: "გაყიდვა / გაქირავება", favorites: "რჩეული", allGeorgia: "მთელი საქართველო",
    hero_pre: "უძრავი ქონება —", hero_post: "ყიდვა, გაყიდვა, ქირაობა ან გაქირავება",
    hero_sub: "შემოწმებული ბინები, სახლები და აპარტამენტები მთელ საქართველოში — დუბლიკატებისა და ყალბი განცხადებების გარეშე. გამჭვირვალე ფასები და ადგილობრივი გუნდის დახმარება.",
    georgia: "საქართველო",
    tab_sale: "გაყიდვა", tab_rent: "ქირა", tab_new: "ახალი კორპუსები", tab_daily: "დღიურად",
    f_city: "ქალაქი", f_anyCity: "ნებისმიერი ქალაქი", f_type: "ტიპი", f_anyType: "ნებისმიერი ტიპი", f_priceTo: "ფასი მდე, $", f_show: "ობიექტების ჩვენება", f_map: "რუკაზე",
    st_verified: "შემოწმებული ობიექტი", st_commission: "ფარული საკომისიო", st_support: "მხარდაჭერა", st_langs: "ენა: RU · EN · GE",
    cat_found: "ნაპოვნია", cat_objects: "ობიექტი", chip_all: "ყველა", f_rooms: "ოთახები", f_anyRooms: "ნებისმიერი", f_studio: "სტუდია",
    f_yearFrom: "წელი დან", f_priceFrom: "ფასი დან, $", f_areaFrom: "ფართობი დან, მ²", f_areaTo: "ფართობი მდე, მ²", f_reset: "გასუფთავება", f_noCommission: "უსაკომისიო", cat_empty: "ამ ფილტრით ობიექტები ჯერ არ არის.",
    foot_about: "უძრავი ქონების მართვა, ქირა და გაყიდვა საქართველოში. მალე — ახალი ქალაქები და მობილური აპლიკაცია.",
    foot_realty: "უძრავი ქონება", foot_company: "კომპანია", foot_mgmt: "ქონების მართვა", foot_cleaning: "დასუფთავება", foot_realtors: "რიელტორები",
    foot_about_l: "კომპანიის შესახებ", foot_contacts: "კონტაქტი", foot_terms: "პირობები", foot_privacy: "კონფიდენციალურობა",
    rooms_short: "ოთახი", per_m2: "მ²-ზე", deal_sale: "გაყიდვა", deal_rent: "ქირა", deal_daily: "დღიურად",
    badge_jk: "კომპლექსი", badge_house: "სახლი", w_from: "დან", w_objects: "ობიექტი",
    crumb_home: "მთავარი", crumb_catalog: "კატალოგი",
    cta_daily: "თარიღების დაჯავშნა", cta_rent: "ქირაობა — განაცხადი", cta_view: "დათვალიერების ჯავშანი",
    sp_type: "ტიპი", sp_area: "ფართობი", sp_rooms: "ოთახები", sp_bath: "სველი წერტილი", sp_floor: "სართული", sp_year: "აშენების წელი", sp_district: "რაიონი", sp_deal: "გარიგება", sp_complex: "კომპლექსი / სახლი",
    boost_badge: "⭐ წახალისებული",
    about_h: "ობიექტის შესახებ", about_p: "მზადაა შესასახლებლად, აქვს დოკუმენტები. გამოდგება საცხოვრებლად და გასაქირავებლად.",
    near_h: "ახლომახლო", near_p: "ზღვა და ბულვარი ფეხით ახლოს, კაფეები, მაღაზიები და ტრანსპორტი. განვითარებული ინფრასტრუქტურა.",
    why_h: "რატომ Baylux", why_p: "შემოწმებულია ჩვენი გუნდის მიერ: დოკუმენტები, რეალური ფოტოები, სამართლიანი ფასი. დაგეხმარებით დათვალიერებასა და გარიგებაში.",
    mgmt_btn: "მსგავსის მართვაში გადაცემა", all_in: "ყველა ობიექტი —", team: "Baylux გუნდი", team_sub: "ვუპასუხებთ 5 წუთში · RU / EN / GE",
    bld_objects_here: "ობიექტი იყიდება და ქირავდება", bld_about_complex: "კომპლექსის შესახებ", bld_about_house: "სახლის შესახებ", bld_units_here: "ობიექტები ამ სახლში",
    th_object: "ობიექტი", th_area: "ფართობი", th_floor: "სართული", th_deal: "გარიგება", th_price: "ფასი",
    bld_cta_title: "გაინტერესებთ ობიექტი —", bld_cta_sub: "შევარჩევთ ბიუჯეტის მიხედვით და მოვაწყობთ ჩვენებას.", bld_lead: "განაცხადის დატოვება", bld_mgmt: "ბინის მართვაში გადაცემა",
    cat_apartment: "ბინები", cat_house: "სახლები", cat_commercial: "კომერციული", cat_office: "ოფისები", cat_warehouse: "საწყობები", cat_land: "მიწის ნაკვეთები", cat_garage: "გარაჟები და პარკინგი", cat_jk: "საცხოვრებელი კომპლექსები", cat_cottage: "კოტეჯები",
    cat_title: "უძრავი ქონების კატეგორიები", cat_subtitle: "სწრაფი გადასვლა — გაყიდვა, ქირა, დღიურად და სერვისები.", show_all: "ყველას ჩვენება", collapse: "დაკეცვა",
    t_apartment: "ბინა", t_studio: "სტუდია", t_house: "სახლი", t_commercial: "კომერციული", t_office: "ოფისი", t_land: "მიწის ნაკვეთი", t_garage: "გარაჟი", t_newbuild: "ახალი კორპუსი",
    af_country: "ქვეყანა", af_city: "ქალაქი", af_deal: "გარიგების ტიპი", af_type: "ობიექტის ტიპი",
    af_complex: "კომპლექსის / სახლის სახელი — სურვილისამებრ", af_complex_ph: "მაგ. Orbi City (არასავალდებულო)",
    af_address: "მისამართი (ქუჩა, სახლი)", af_address_ph: "შერიფ ხიმშიაშვილის ქ. 1",
    af_mapnote: "წერტილი რუკაზე — მისამართის მიხედვით ავტომატურად. შეგიძლიათ შეასწოროთ დაჭერით (ჩართეთ სატელიტი):",
    af_geo_auto: "📍 წერტილი დაყენებულია მისამართის მიხედვით — შეამოწმეთ და საჭიროების შემთხვევაში გადაიტანეთ რუკაზე დაჭერით.",
    af_geo_manual: "✓ წერტილი არჩეულია ხელით.", af_geo_set: "✓ წერტილი არჩეულია", af_geo_hint: "შეიყვანეთ მისამართი — წერტილი თავად გამოჩნდება, ან დააჭირეთ რუკას",
    af_price: "ფასი", af_currency: "ვალუტა", af_area: "ფართობი, მ²", af_rooms: "ოთახები", af_bath: "სველი წერტილი", af_floor: "სართული", af_year: "აშენების წელი",
    af_about: "აღწერა", af_about_ph: "მოკლედ ობიექტის შესახებ", af_amen: "კეთილმოწყობა (სურვილისამებრ)", af_nc: "მყიდველისგან საკომისიოს გარეშე",
    af_phone: "საკონტაქტო ტელეფონი — საქართველო, +995 (სავალდებულო)", af_tg: "Telegram კონტაქტისთვის (@username) — სურვილისამებრ", af_tg_ph: "@username (არასავალდებულო)",
    af_cur_photos: "მიმდინარე ფოტოები (დააჭირეთ ✕ მოსაშორებლად)", af_add_photos: "სხვა ფოტოების დამატება", af_photos: "ფოტოები (10-მდე, ავტომატურად იკუმშება)", af_newphotos: "ახალი ფოტო",
    af_saving: "ვინახავ…", af_submit: "მოდერაციაზე გაგზავნა", af_submit_edit: "შენახვა და მოდერაციაზე გაგზავნა", af_err: "გაგზავნის შეცდომა. შეამოწმეთ ველები და სცადეთ თავიდან.",
    af_alert_addr: "მიუთითეთ ობიექტის მისამართი.", af_alert_phone: "მიუთითეთ ქართული ტელეფონის ნომერი (+995). მაგ.: +995 555 12 34 56.",
    af_done_add_h: "✅ განცხადება გაგზავნილია მოდერაციაზე", af_done_edit_h: "✅ ცვლილებები გაგზავნილია მოდერაციაზე",
    af_done_add_p: "ჩვენ შევამოწმებთ და გამოვაქვეყნებთ.", af_done_edit_p: "განცხადება მოიხსნა გამოქვეყნებიდან და ხელახლა შემოწმების შემდეგ კვლავ გამოჩნდება.",
    af_done_tail: "სტატუსი — განყოფილებაში „ჩემი განცხადებები“.", af_my: "ჩემი განცხადებები",
    am_furniture: "ავეჯი", am_balcony: "აივანი", am_terrace: "ტერასა", am_parking: "პარკინგი", am_euro: "ევრორემონტი", am_norenov: "რემონტის გარეშე", am_ac: "კონდიციონერი", am_elevator: "ლიფტი",
    cab_title: "პირადი კაბინეტი", cab_login_p: "შედით Telegram-ით — იხილავთ ბოტით გაგზავნილ თქვენს განცხადებებს და მათ სტატუსს.", cab_or: "ან შედით Telegram-ვიჯეტით:",
    cab_bot_a: "განცხადებები ემატება ბოტში", cab_bot_b: "(ბრძანება /start ან მენიუ).",
    my_title: "ჩემი განცხადებები", my_logout: "გასვლა", cab_objs: "თქვენი ობიექტები", cab_addnew: "ახლის დასამატებლად — ბოტში @baylux_leads_bot (/start).",
    my_pending: "მოდერაციაზე", my_approved: "გამოქვეყნებული", my_rejected: "მოხსნილი / უარყოფილი",
    my_view: "ნახვა →", my_notvisible: "საიტზე არ ჩანს", my_edit: "✏️ რედაქტირება", my_del: "🗑 წაშლა", my_deleting: "ვშლი…",
    my_empty: "ჯერ არ არის განცხადებები. გახსენით ბოტი და გაგზავნეთ /start.", my_del_confirm: "წავშალო ეს განცხადება? ქმედება შეუქცევადია.", my_del_fail: "ვერ წაიშალა. სცადეთ მოგვიანებით.", my_neterr: "ქსელის შეცდომა.",
    ab_title: "Baylux-ის შესახებ",
    ab_p1: "Baylux — უძრავი ქონების კომპანია ბათუმში (საქართველო). ჩვენ გეხმარებით ბინის ყიდვაში, გაყიდვაში, ქირაობასა და გაქირავებაში, ასევე ვიღებთ ობიექტებს სრულ მართვაში. ვმუშაობთ როგორც ადგილობრივი გუნდი — მოვდივართ, ვაჩვენებთ და გარიგებას ადგილზე ვუძღვებით, და არა ქოლ-ცენტრიდან.",
    ab_h_do: "რას ვაკეთებთ", ab_do1: "უძრავი ქონების გაყიდვა — ახალი (პირველადი) და მეორადი.", ab_do2: "ქირა — გრძელვადიანი და დღიური.", ab_do3: "ქონების მართვა — სტუმრები, დასუფთავება, რემონტი, ანგარიშები.", ab_do4: "დასუფთავება და თანმხლები სერვისები.",
    ab_h_why: "რატომ Baylux", ab_why1: "შემოწმებული ობიექტები — დუბლიკატებისა და ფეიქების გარეშე.", ab_why2: "გამჭვირვალე ფასები და პირობები, ფარული საკომისიოს გარეშე.", ab_why3: "მხარდაჭერა რუსულ, ინგლისურ და ქართულ ენებზე.",
    ab_h_plans: "გეგმები", ab_plans_p: "ამჟამად ვმუშაობთ ბათუმში. გეგმებში — საქართველოს სხვა ქალაქები და საკუთარი მობილური აპლიკაცია.", ab_btn_add: "განცხადების განთავსება", ab_btn_contacts: "კონტაქტი",
    co_title: "კონტაქტი", co_p: "ვუპასუხებთ 5 წუთში. მოგვწერეთ თქვენთვის მოსახერხებელი გზით — რუსულად, ინგლისურად ან ქართულად.",
    co_h_where: "სად ვართ", co_where: "📍 ბათუმი, საქართველო. ვმუშაობთ მთელ ქალაქსა და გარეუბნებში (გონიო, მახინჯაური, ჩაქვი).",
    co_h_post: "ობიექტის განთავსება", co_post: "უძრავი ქონების გაქირავება ან გაყიდვა შეგიძლიათ პირდაპირ საიტზე — ღილაკი „გაყიდვა / გაქირავება“, ან ჩვენი Telegram-ბოტით @baylux_leads_bot.", co_foot: "Baylux · უძრავი ქონება ბათუმში, საქართველო.",
    tm_title: "გამოყენების პირობები", tm_disclaimer: "საბაზისო რედაქცია. საბოლოო ტექსტი უნდა შეამოწმოს იურისტმა საქართველოს კანონმდებლობის გათვალისწინებით.",
    tm_h1: "1. ზოგადი დებულებები", tm_p1: "Baylux-ის საიტი — პლატფორმა ბათუმში უძრავი ქონების განცხადებების განთავსებისა და ძიებისთვის. საიტით სარგებლობით თქვენ ეთანხმებით ამ პირობებს.",
    tm_h2: "2. განცხადებები და მოდერაცია", tm_p2: "განცხადებებს ათავსებენ მომხმარებლები და გამოქვეყნებამდე მოწმდება მოდერატორის მიერ. Baylux უფლებამოსილია უარყოს ან მოხსნას განცხადება, რომელიც არღვევს წესებს, შეიცავს არასწორ მონაცემებს ან სხვის კონტენტს.",
    tm_h3: "3. პასუხისმგებლობა", tm_p3: "განცხადებაში მითითებული ინფორმაციისა და ფოტოების სიზუსტეზე პასუხს აგებს მისი განმთავსებელი მომხმარებელი. Baylux არ არის მხარეთა შორის გარიგების მხარე, თუ სხვაგვარად არ არის შეთანხმებული.",
    tm_h4: "4. კონტენტი", tm_p4: "განცხადების განთავსებით მომხმარებელი ადასტურებს, რომ ფლობს გამოყენებულ ფოტოებსა და აღწერებზე უფლებებს და თანხმობას აძლევს მათ გამოქვეყნებას საიტზე.",
    tm_h5: "5. კონტაქტი", tm_p5: "კითხვებისთვის — განყოფილება „კონტაქტი“. პირობები შეიძლება განახლდეს; აქტუალური რედაქცია ქვეყნდება ამ გვერდზე.",
    pv_title: "კონფიდენციალურობის პოლიტიკა", pv_h_what: "რა მონაცემებს ვამუშავებთ",
    pv_what1: "საკონტაქტო მონაცემები (ტელეფონი, @username), მითითებული განცხადების განთავსებისას.", pv_what2: "Telegram-ის იდენტიფიკატორი Telegram-ით შესვლისას.", pv_what3: "განცხადების მონაცემები: ტიპი, მისამართი, ფასი, აღწერა, ფოტოები, წერტილი რუკაზე.",
    pv_h_why: "რისთვის", pv_why: "განცხადებების გამოსაქვეყნებლად, თქვენს ანგარიშთან დასაკავშირებლად, მოდერაციის ჩასატარებლად და ობიექტთან დაკავშირებით თქვენთან საკონტაქტოდ.",
    pv_h_store: "შენახვა", pv_store: "მონაცემები ინახება ინფრასტრუქტურის მომწოდებელთან (Supabase) და გამოიყენება მხოლოდ სერვისის მუშაობისთვის. ჩვენ არ ვყიდით თქვენს მონაცემებს მესამე პირებზე.",
    pv_h_rights: "თქვენი უფლებები", pv_rights: "შეგიძლიათ წაშალოთ თქვენი განცხადებები განყოფილებაში „ჩემი განცხადებები“ ან მოითხოვოთ ანგარიშის წაშლა „კონტაქტის“ მეშვეობით.",
    add_title: "განცხადების განთავსება", add_login_p: "ჯერ შედით Telegram-ით — განცხადება დაუკავშირდება თქვენს ანგარიშს და შეძლებთ მის მართვას.", add_intro: "შეავსეთ მონაცემები, მონიშნეთ წერტილი რუკაზე და დაამატეთ ფოტოები. მოდერატორის შემოწმების შემდეგ განცხადება გამოჩნდება საიტზე. სტატუსი — განყოფილებაში „ჩემი განცხადებები“.",
    fav_title: "რჩეულები", fav_empty: "ჯერ ცარიელია. დააჭირეთ ♡ ობიექტების ბარათებზე — ისინი აქ გამოჩნდება.", fav_to_catalog: "კატალოგის გახსნა →", fav_open: "გახსნა", fav_remove: "მოშორება",
    home_map_h: "საცხოვრებელი კომპლექსები და სახლები რუკაზე", home_map_p: "ერთი ნიშანი — ერთი შენობა. გახსენით შენობა და იხილეთ ყველა ბინა, რომელიც იყიდება ან ქირავდება.", home_map_btn: "კატალოგის გახსნა ფილტრებით →",
    home_fresh_h: "ახალი ობიექტები", home_fresh_p: "უახლესი ბინები და აპარტამენტები Baylux-ის ბაზაში.",
    svc_h: "რას ვაკეთებთ", svc_p: "არა მხოლოდ განცხადებების ვიტრინა — უძრავ ქონებასთან მუშაობის სრული ციკლი საქართველოში.",
    svc_mgmt_h: "მართვა", svc_mgmt_p: "გადმოგვეცით ბინა — ვიზრუნებთ სტუმრებზე, დასუფთავებაზე, რემონტსა და ანგარიშებზე. თქვენ იღებთ შემოსავალს, ჩვენ ვიღებთ რუტინას.", svc_mgmt_btn: "მართვაში გადაცემა →",
    svc_rent_h: "ქირა", svc_rent_p: "დღიურად ქალაქის სტუმრებისთვის და გრძელვადიანად მათთვის, ვინც გადმოდის. სამართლიანი ფასები, შემოწმებული ობიექტები, ხელშეკრულება.", svc_rent_btn: "ქირაობა ან გაქირავება →",
    svc_sale_h: "გაყიდვა და ინვესტიცია", svc_sale_p: "დაგეხმარებით საცხოვრებელი ბინის ყიდვაში ან ზღვისპირა ახალ კორპუსში ინვესტიციაში. გარიგებას ვუძღვებით დათვალიერებიდან გასაღებამდე.", svc_sale_btn: "ყიდვა ან გაყიდვა →",
    why_local_h: "ადგილობრივები", why_local_p: "გუნდი ბათუმში — მოვალთ, გაჩვენებთ და ადგილზე დაგეხმარებით.",
    why_nodup_h: "დუბლიკატების გარეშე", why_nodup_p: "სუფთა ბაზა: ერთი ობიექტი — ერთი განცხადება, ნაგვის გარეშე.",
    why_clear_h: "გამჭვირვალედ", why_clear_p: "რეალური ფასები და პირობები. ფარული საკომისიოს გარეშე.",
    why_fast_h: "სწრაფად", why_fast_p: "განაცხადი და ჯავშანი საიტით ან WhatsApp-ით — წუთში.",
  },
};

export function t(lang, key) {
  const l = DICT[lang] ? lang : "ru";
  return DICT[l][key] || DICT.ru[key] || key;
}

// Названия типов объектов хранятся по-русски; переводим для отображения.
const TYPE_KEY = {
  "Квартира": "t_apartment", "Студия": "t_studio", "Дом": "t_house", "Коммерция": "t_commercial",
  "Офис": "t_office", "Участок": "t_land", "Гараж": "t_garage", "Новостройка": "t_newbuild",
};
export function typeLabel(lang, type) {
  const k = TYPE_KEY[type];
  return k ? t(lang, k) : (type || "");
}

// Удобства хранятся по-русски (значение фильтра); переводим только подпись.
const AMEN_KEY = {
  "Мебель": "am_furniture", "Балкон": "am_balcony", "Терраса": "am_terrace", "Парковка": "am_parking",
  "Ремонт «евро»": "am_euro", "Без ремонта": "am_norenov", "Кондиционер": "am_ac", "Лифт": "am_elevator",
};
export function amenLabel(lang, a) {
  const k = AMEN_KEY[a];
  return k ? t(lang, k) : (a || "");
}

// Названия городов/районов хранятся по-русски; переводим известные.
const CITY_TR = {
  en: { "Батуми": "Batumi", "Тбилиси": "Tbilisi", "Кобулети": "Kobuleti", "Гонио": "Gonio", "Чакви": "Chakvi", "Кутаиси": "Kutaisi", "Рустави": "Rustavi", "Бакуриани": "Bakuriani", "Гудаури": "Gudauri", "Местиа": "Mestia", "Махинджаури": "Makhinjauri" },
  ka: { "Батуми": "ბათუმი", "Тбилиси": "თბილისი", "Кобулети": "ქობულეთი", "Гонио": "გონიო", "Чакви": "ჩაქვი", "Кутаиси": "ქუთაისი", "Рустави": "რუსთავი", "Бакуриани": "ბაკურიანი", "Гудаури": "გუდაური", "Местиа": "მესტია", "Махинджаури": "მახინჯაური" },
};
export function cityLabel(lang, name) {
  if (lang === "ru" || !CITY_TR[lang]) return name || "";
  return CITY_TR[lang][name] || name || "";
}
